### ISSUE TITLE
重启电脑后链接失效

### ISSUE THREAD

**Issue by bianliangpai** [tiaod/day-progress#2]
运行 npm run serve 后，将 Network 的链接复制到 Lively 里，可以正常看到预期结果
但重启电脑后，桌面会显示链接失效

还需要什么额外操作才能部署到 github action 吗？或者其他不依赖本地、可以持续运行的方式？
感谢

**Comment by tiaod** [comment]
可以使用我提供的在线demo呀，地址在readme里面

**Comment by bianliangpai** [comment]
readme 的链接地址打开会报这个错
403 Forbidden
Code: AccessDenied
Message: You are denied by bucket referer rule
Key: day-progress/index.html
RequestId: NWVjYjVjYzBfMjEyZDdhNjRfNTFkZV8zNWJkYjg4
TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQ5YWUxMjNkYTk3NzdjZmZlMDQzOTgxOThkOTNlOWFkZjBjZjY5OGU2ZTBmZWM0MmE4YjI2OWU3YjQ2YTU5NTM=

**Comment by bianliangpai** [comment]
曲线救国了一把，暂时能用了。
虽然我没法打开页面，但把链接直接拷贝到 lively 里也能用。显示配置的相关的链接后缀是相同的，我在本地运行一下、把配置相关的链接复制到 demo 地址的后面，两部分一起拷贝到 lively 里就会是想要的效果了。
感谢输出，工具很好用。

**Comment by tiaod** [comment]
@bianliangpai 我刚发布了一份到github pages，试试这个链接
https://tiaod.github.io/day-progress/

**Comment by bianliangpai** [comment]
> @bianliangpai 我刚发布了一份到github pages，试试这个链接
> https://tiaod.github.io/day-progress/

这个可以正常打开了，Lively的链接也换成这个了~
